	tilepal 0, GRAY, ROOF, ROOF, ROOF, PRIORITY_ROOF, ROOF, ROOF, ROOF
	tilepal 0, WATER, WATER, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, WATER, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, GRAY, PRIORITY_ROOF, PRIORITY_ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, YELLOW, BROWN
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, PRIORITY_ROOF, PRIORITY_ROOF
	tilepal 0, ROOF, ROOF, WATER, WATER, ROOF, ROOF, ROOF, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, ROOF, ROOF, WATER, WATER, ROOF, GRAY, GRAY, GRAY
	tilepal 0, ROOF, ROOF, ROOF, GRAY, GRAY, GRAY, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY
	tilepal 0, WATER, ROOF, ROOF, BROWN, GRAY, GRAY, ROOF, ROOF

rept 32
	db $ff
endr

	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, YELLOW, ROOF, YELLOW, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, BROWN, YELLOW
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, ROOF, ROOF, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, ROOF, ROOF, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
