	tilepal 0, GRAY, BROWN, BROWN, RED, GREEN, GREEN, GRAY, RED
	tilepal 0, RED, RED, PRIORITY_ROOF, PRIORITY_ROOF, PRIORITY_ROOF, PRIORITY_ROOF, PRIORITY_ROOF, PRIORITY_ROOF
	tilepal 0, PRIORITY_ROOF, PRIORITY_ROOF, PRIORITY_ROOF, GREEN, WATER, GREEN, BROWN, BROWN
	tilepal 0, RED, RED, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, RED, RED, BROWN, YELLOW, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, WATER, WATER, BROWN, BROWN, BROWN, YELLOW
	tilepal 0, YELLOW, GRAY, GRAY, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, RED, BROWN, WATER, WATER, BROWN, GREEN, BROWN, BROWN
	tilepal 0, BROWN, WATER, GRAY, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, WATER, GRAY, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, GREEN, GREEN, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, GREEN, GREEN, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, TEXT
	tilepal 1, BROWN, BROWN, BROWN, RED, RED, RED, RED, RED
	tilepal 1, RED, RED, RED, RED, RED, RED, RED, RED
	tilepal 1, RED, RED, RED, RED, YELLOW, YELLOW, YELLOW, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, YELLOW
	tilepal 1, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 1, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 1, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 1, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN
